apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: cfbn89/demo-app:sha-d15256b
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 1m }
        - setWeight: 50
        - pause: { duration: 1m }
        - setWeight: 100